name: CI Pipeline

on:
  push:
    branches:
      - "*"  
      - "integration-vm-project"  
  pull_request:
    branches:
      - "main"  
      - "integration-vm-project"  

jobs:
  lint-and-test:
    name: Run Linting and Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db  # Placeholder, real values set later
          POSTGRES_USER: test_user  
          POSTGRES_PASSWORD: test_password  
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set Environment Variables from Secrets
        run: |
          echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV  # ✅ Fix: Ensure pytest can find modules

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest black isort
          pip install coverage pytest

      - name: Format Code (black & isort)
        run: |
          black .
          isort .

      - name: Run Linter (flake8)
        run: |
          flake8 . --ignore=E501,W291,W503,E303

      - name: Run Tests (pytest) with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}  # ✅ Fix: Set PYTHONPATH explicitly
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          coverage run -m pytest --maxfail=5 --disable-warnings
          coverage xml
          coverage report
